### PR TITLE
Fake RMU40 room temperature sensor

### PR DESCRIPTION
**Pull request by egisz**
I managed to fake RMU40 temperature sensor.
Created branch in my [repo](https://github.com/egisz/esphome-nibe/tree/fake-rmu-sensor), [fake-rmu-sensor] (https://github.com/elupus/esphome-nibe/compare/master...egisz:fake-rmu-sensor?expand=1) branch

- Added ~~number template~~ home asssistant sensor entity `rmu40_fake_temp` in esp config file:

```
# Home Assistant Sensor - https://esphome.io/components/sensor/homeassistant.html
# used to map any HA temperature sensor to pretend as RMU40 room temperature sensor.
# sensor id must be passed to nibegw component
sensor:
  - platform: homeassistant
    id: rmu40_fake_temp
    entity_id: sensor.shellyplusht_08b61fcad31c_temperature # replace to your sensorId
```

- Added extra nibegw parameter [rmu40_fake_temp_sensor_id](https://github.com/elupus/esphome-nibe/compare/master...egisz:esphome-nibe:fake-rmu-sensor?expand=1#diff-b75cb421a6528eb22f460ea523de189dc96946ded9e29f8aaadacc0feeb5a51fR66) to map this sensor to nibegw component.

```
# Configure NibeGW
nibegw:
  udp:
    target:
        ...
  rmu40_fake_temp_sensor_id: rmu40_fake_temp
```

- Updated `NibeGwComponent::callback_msg_token_received` function to insert fake sensor's value instead of constant value.

Thats it, now I can control RMU40 sensor from HA ~~both manually adjusting sensor, or by simple automation which triggers on my~~ automatically on each Shelly H&T temperature change.

image

### CODE REVIEW

**Comment by elupus** [comment]
Yup, this is close to how i thought to do it. But needs to be a bit more generalised.

**Comment by elupus** [comment]
The 7 offset is strange but known: https://github.com/yozik04/nibe/blob/2278e2e2f71d6078440ecf239eb76b6ce53199fd/nibe/connection/nibegw.py#L691

**Comment by egisz** [comment]
I changed esphome dummy sensor type to [Home Assistant Sensor](https://esphome.io/components/sensor/homeassistant.html), now it automatically follows predefined sensor, no automations needed :)

**Comment by elupus** [comment]
I've made an attempt at this too: https://github.com/elupus/esphome-nibe/pull/60 it's getting there :). Set points works too.

**Comment by elupus** [comment]
I've merged an alternate solution now. Seem to work mostly, very little tests.

**Pull request closed without merging**
